name: Validate docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-docs:
    name: validate-docs
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Run swagger validation
        uses: readmeio/rdme@v8
        with:
          rdme: openapi:validate swagger.json
